# Config file for the acts_as_solr plugin.
#
# If you change the host or port number here, make sure you update
# them in your Solr config file

development:
  url: http://0.0.0.0:8982/solr
  options: -m 128m
  timeout: 0

production:
  url: http://127.0.0.1:8983/solr
  options: -m 192m
  timeout: 0

test: &TEST
  url: http://0.0.0.0:8981/solr
  options: -m 128m
  timeout: 0

cucumber:
  <<: *TEST
